apiVersion: v1
kind: Service
metadata:
  name: apollo-router
  namespace: stayflexi
  labels:
    app: apollo-router
spec:
  selector:
    app: apollo-router
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      name: http
  type: ClusterIP
