apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: stayflexi
  labels:
    app: analytics-service
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
  - name: http
    protocol: TCP
    port: 3008
    targetPort: http
