apiVersion: v1
kind: Service
metadata:
  name: ota-service
  namespace: stayflexi
  labels:
    app: ota-service
spec:
  type: ClusterIP
  selector:
    app: ota-service
  ports:
  - name: http
    protocol: TCP
    port: 3007
    targetPort: http
