apiVersion: v1
kind: Namespace
metadata:
  name: stayflexi
  labels:
    name: stayflexi
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: stayflexi-staging
  labels:
    name: stayflexi-staging
    environment: staging
