apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: stayflexi
  labels:
    app: inventory-service
spec:
  type: ClusterIP
  selector:
    app: inventory-service
  ports:
  - name: http
    protocol: TCP
    port: 3004
    targetPort: http
